### ISSUE TITLE
Several Incorrect nozzle sizes

### ISSUE THREAD

**Issue by nickthetait** [alephobjects/print_profiles#8]
Was testing out T-glase for on my Mini, having strange inter-layer separation and under-extrusion. I discovered that the nozzle size was [incorrectly set to 0.6mm](https://github.com/alephobjects/print_profiles/blob/master/cura/Mini/T-Glase_high-clarity_mini.ini#L7). Went ahead and checked around for other nozzle size discrepancies. Below are the erroneous ones I found. 

Mini (0.5 nozzle):
* T-glase high clarity
* Tritan high clarity
* Nylon high strength

Taz (0.35 nozzle):
* Ninjaflex

Taz (0.5 nozzle):
* T-glase high clarity
* Tritan high clarity
* Nylon high strength

Just want to double check with @brentmac and @reprapperMC before I fix these.

**Comment by brentmac** [comment]
Those nozzle sizes are by design. You can get higher strength and clarity with some materials (pretty much just PET's and Nylons) by telling it that it has a larger nozzle than it has, Taulman goes into it on his t-glase page. It comes at the expense of surface finish, so that's why we only do it for high strength/clarity profiles.

Flexy's have always been shipped with a 0.5 nozzle, but that's being upped to 0.6mm for the v2 that we're about to roll out.

Can you send me the t-glase gcode that you were having issues with? The t-glase profiles have been pretty solid in my testing, it could be something else going on.

**Comment by nickthetait** [comment]
Glad that I asked!

Trying to print the 1mm wall version of [this guy](https://www.youmagine.com/designs/stacking-box). I loaded the T-glase profile, then modified:
Shell thickness (1.2 -> 1.0)
Fill Density (30% -> 0%)
